### ISSUE TITLE
Square up LO

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#100]
To reduce the mixer temperature coefficients, LO AM-PM sensitivity, and distortion, it would be very useful to increase the slew rate and square it up.

![image](https://user-images.githubusercontent.com/1338946/121524004-22083380-c9f7-11eb-963d-eda348e525b6.png)

This could be done in differential signalling. In that case we would want a differential AA filter or two matched filters and a high gain, low jitter, limiting clock buffer. If possible, that clock buffer would replace the amplifier IC13A/B.
Maybe we can even go differentially (differential clock buffer) into the mixer LO at significant benefit (LO isolation). We should just double-check that the GND pin opposing LO is actually the other end of the LO balun winding).
A frequency-scaled version of the [AD9912-EVAL FDBK-IN reconstruction filter](https://www.analog.com/media/en/technical-documentation/user-guides/EVAL-AD9912A_PCBZ_UG-475.pdf) would be a good start. Also [AN-837](https://www.analog.com/media/en/technical-documentation/application-notes/351016224AN_837.pdf) has some good advice.

![image](https://user-images.githubusercontent.com/1338946/121525250-63e5a980-c9f8-11eb-8c37-6a8b9431bce7.png)
![image](https://user-images.githubusercontent.com/1338946/121525271-6b0cb780-c9f8-11eb-9859-fb36143d18c1.png)
![image](https://user-images.githubusercontent.com/1338946/121525300-73fd8900-c9f8-11eb-8266-0b492fe7dbde.png)

**Comment by gkasprow** [comment]
MAybe use sth like [LTC6957](https://www.analog.com/media/en/technical-documentation/data-sheets/6957fb.pdf)?
LTC6957-4 has CMOS Logic, Complementary Outputs

**Comment by gkasprow** [comment]
@jordens, what cut-off frequency would you like to have?

**Comment by gkasprow** [comment]
what's wrong with the LTCC filters we use right now? We can use more of them to get rid of aliasing.

**Comment by jordens** [comment]
The LTCC filters are fine but single ended. With a balanced filter, differential (in and out) clock buffer we'd be all differential and save the balun as well.
But honestly idea is a bit more experimental and risky than I'd dare put into the next iteration without prototyping it first. Let's leave it out and open for now. Maybe somebody wants to pursue this as an experiment. I'd certainly be interested in seeing the result.

**Comment by gkasprow** [comment]
I thought you want to put the filter before the buffer to make perfect sine and then convert it to perfect square wave.

**Comment by jordens** [comment]
Yes. Filter before buffer.
My goal with the balanced filters would have been to have then entire chain (DDS, filter, buffer, Mixer LO) balanced and never convert to/from unbalanced. That's what they do

**Comment by gkasprow** [comment]
OK. it's better to design a simple PCB with components and connect only IN, OUT and supply
I't put there entire chain; filter, clock buffer, mixer, and output filter. I can also shape it in such way that you can solder it on top of Phaser board without using long wires. - just remove old components from PCB and fit everything under the shield.
the only signal that would need to be delivered is twisted pair from DDS

**Comment by jordens** [comment]
If you can find the space on the board (for a balanced filter + buffer as a bypass to the chain of dds output balun + LTCC filter + pad + RF amplifier) then add them. Otherwise I'd say leave it as is.

[LMK1D2102RGTR](https://www.ti.com/lit/ds/symlink/lmk1d2102.pdf?ts=1659002864882&ref_url=https%253A%252F%252Fwww.google.com%252F) is also an as buffer.

**Comment by gkasprow** [comment]
I have some place on the bottom so can try to install it there.

**Comment by gkasprow** [comment]
I'm not sure if LVDS can drive 10dBm (1.2V peak) into a 100Ohm load.
It usually has only 4mA of current.
LVPECL is a better option and would give much better rise time than CMOS.
CMOS output is too strong and we would have to attenuate it.

**Comment by jordens** [comment]
The mixer LO is 50 Ohm, also if we use it differential.

**Comment by gkasprow** [comment]
right, that's even worse in case of LVDS

**Comment by gkasprow** [comment]
What cutoff frequency do you want for the differential path? 160MHz?

**Comment by gkasprow** [comment]
@jordens and what order of the filter do you need?

**Comment by gkasprow** [comment]
@jordens what about such circuit?
![image](https://user-images.githubusercontent.com/4325054/181748613-03d9b30b-5997-4a81-af49-59492f089ed5.png)

**Comment by gkasprow** [comment]
and filter characteristics
![image](https://user-images.githubusercontent.com/4325054/181748762-22cd0aad-310c-4c61-821f-984456cb633e.png)

**Comment by gkasprow** [comment]
the driver resistance is very low (open emitter). Maybe we should add two 24Ohm resistors to make it a 50Ohm differential...
The driver provides 1.6Vpp, but with matching that would be halved.

**Comment by jordens** [comment]
The LO port is a very non-linear one anyway (it's two series pairs of diodes): VSWR against 50 Ohm 7 dBm is 2.5, and 50 Ohm 10 dBm is 3.5. As long as you saturate them well and the buffer chip is happy with the load, and there is no long lines between buffer and mixer, we should be fine without any termination (R100, 101, 102). Maybe series resistors to limit the current would be better.

As filter, with 250 MHz Nyquist, I'd go for something like this (balanced, i.e. doubled up; but component values don't matter now since it's a variant anyway).
![image](https://user-images.githubusercontent.com/1338946/182125576-928ce579-3d3e-4098-b526-d5624aaa2db2.png)

**Comment by gkasprow** [comment]
We need R100, 101, and 102 because they act as pulldown. And these pulldown resistors limit the current. The LVPECL is an open emitter output stage.
I marked these filter components as DNP and placed the values you suggested.

**Comment by jordens** [comment]
Ack. I got it now.
Looking at the VSWR the LO port of the mixer is more like an "average" 15 - 20 Ohm impedance for a sine wave at 10-7 dBm. As would be expected from 2 diodes. With that in mind R100/R102 could actually be large (e.g. 100 Ohm) to maximize power into LO and R101 to something lower like 0R to adjust the working point.
All up for tuning.

**Comment by gkasprow** [comment]
When you look at the datasheet, the output voltage amplitude does not depend much on the load resistor. You only change the offset. But yes, a higher value will dissipate less power.

**Comment by gkasprow** [comment]
I mean this plot
![image](https://user-images.githubusercontent.com/4325054/182183751-8a138108-09c7-4cb7-ac42-80f9d24a31eb.png)

**Comment by jordens** [comment]
Yep.
