### ISSUE TITLE
parts availability

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Pounder#101]
https://github.com/sinara-hw/Kasli/issues/97

**Comment by gkasprow** [comment]
@jordens it's impossible to source MCP23017 in any package.
What about adding footprint for [PCF8575](https://www.ti.com/lit/ds/symlink/pcf8575.pdf?ts=1654434860246&ref_url=https%253A%252F%252Fwww.google.com%252F) or [PCA9539](https://www.ti.com/lit/ds/symlink/pca9539.pdf?ts=1654510586170&ref_url=https%253A%252F%252Fwww.google.com%252F) ?

**Comment by jordens** [comment]
Please do use an available one!
Either is fine from the software perspective.

**Comment by gkasprow** [comment]
sure
