### ISSUE TITLE
DDS baluns/termination are wrong

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#103]
The source output impedance after the baluns (TR9 etc) is 100 Ohm currently. The filters want 50 Ohm. (The eval board also has a 100 Ohm single ended output impedance from DAC1_OUT into 50 Ohm filters/SMA output which doesn't sound optimal).
We can either make the source termination R24...R35 25R or use TC2-1TX+ as baluns. The latter gives more power and is still within DAC compliance.

**Comment by gkasprow** [comment]
fixed
![image](https://user-images.githubusercontent.com/4325054/181616140-5246d47a-b797-4336-8196-2ceb9e79837e.png)

**Comment by jordens** [comment]
Just to remind myself of the context:

Datasheet says:

![image](https://user-images.githubusercontent.com/1338946/182128824-226d906c-2046-4603-9cb1-457df5f8670b.png)

While the text is consistent, the figure is wrong.
Note the missing resistors at the source side of the balun. The Source would be ~100 k impedance.

Eval board has:

![image](https://user-images.githubusercontent.com/1338946/182128685-f6025697-425c-4e0d-97ea-0586f641bace.png)

This is also wrong.
The 50 R are populated. Hence the source impedance is 100 R. The balun is 1:1. DAC_OUT is 50 R (filter and SMA)

Various ANs from ADI with different information:

https://www.analog.com/media/en/technical-documentation/application-notes/an_912.pdf looks trustworthy and is consistent.

![image](https://user-images.githubusercontent.com/1338946/182130505-6b724654-f52b-4fba-9110-c753d190a3df.png)

https://www.analog.com/media/en/training-seminars/tutorials/MT-019.pdf similarly consistent.

![image](https://user-images.githubusercontent.com/1338946/182130051-8312460d-b972-4cc5-8531-7c5cab40ebcf.png)

https://www.analog.com/media/en/training-seminars/design-handbooks/Technical-Tutorial-DDS/Section6.pdf is wrong.

![image](https://user-images.githubusercontent.com/1338946/182130170-052b45c5-16c1-44ff-bb1b-51827b32196b.png)

The AD9850 is also an unterminated current source with 100 k impedance.

Some Analog forum posts indicating the obvious, that this is indeed a current source and the source termination should match the load impedance:

https://ez.analog.com/dds/f/q-a/536170/ad9959-output-impedance
https://ez.analog.com/dds/f/q-a/28841/ad9959---no-ac-output-improper-termination
