### ISSUE TITLE
better panel ADC labels

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#104]
The two MCX ADC inputs currently labeled ADC0 and ADC1. This is confusing as it collides with the labels of the Stabilizer SMA ADC inputs. Better labels would be "AUX ADC0" and "AUX ADC1", assuming that fits.

![image](https://user-images.githubusercontent.com/1338946/180815861-bbd9f031-013c-4e79-844f-bc2d4b1b89bb.png)

**Comment by gkasprow** [comment]
fixed
![image](https://user-images.githubusercontent.com/4325054/181605568-be11db0c-9577-4a54-8d80-3aa8e62b2e0a.png)
