### ISSUE TITLE
Add i2c eeprom 

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#106]
To identify Pounder and distinguish it from other mezzanines, we should add an eeprom (Driver already has it) on the I2C bus.
Nominated for v1.2 if it's not too late.

**Comment by jordens** [comment]
We could use the different i2c switch as an indicator. But that's obviously a shortsighted idea as nothing prevents other mezzanines from using those as well.

**Comment by gkasprow** [comment]
we can use another switch as a revision indicator (4 bits) and board type indicator (another 4 bits)

**Comment by gkasprow** [comment]
On the other side, it would be good to do it as on the Driver mezzanine

**Comment by gkasprow** [comment]
I added an EEPROM
