### ISSUE TITLE
wrong power detector VTGT

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#108]
Turns out voltage on pin 12 is 0.88V. There is a mistake on the schematic - R16 and R63 values should be switched. With proper resistors power meter works properly.

_Originally posted by @MatBier in https://github.com/sinara-hw/Pounder/issues/95#issuecomment-1377518420_
      

Both channels.

**Comment by jordens** [comment]
R63A/B: 750R
R14A/B: 1k2

**Comment by gkasprow** [comment]
added fixed PnP and BOM files to existing release
