### ISSUE TITLE
vga

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#13]
Is 18dB max enough gain for the VGA? Would it be easier to just add the same digital attenuator on Urukul etc followed by a fixed-gain pre-amp?

**Comment by dnadlinger** [comment]
Wouldn't the VGA typically be used only to fine-tune the gain after you've used an external amplifier (e.g. an amplified photodiode) to get you close enough? Sure, having to fiddle with external attenuators/multiple cascaded amps/etc. is annoying, but it seems like an 16 dB window is wide enough to easily hit when designing/choosing the detection chain.

Without having calculated actual numbers, it seems like 18 dB gain ought to give you decent performance at -20 dBm input power or something like that.

**Comment by jordens** [comment]
I would also think that a step attenuator (that's already present on the BOM) plus a fixed amplifier (that's also present on the BOM) is better than the PGA. Wider range, no more useful step sizes. Maybe also less insertion loss and thus better overall noise figure than the PGA. Also saves at least one transformer.

**Comment by jordens** [comment]
* If you go for the step attenuators, hook them up in daisy chain with the two existing attenuators, but use individual LE lines (4 LE, 1 CLK, 1 SDI, 1 SDO).
* No need to wire ATT_RSTn on any of the attenuators IMO.
* OSC_en, DDS_RESET, EXT_CLK_SEL and the attenuator lines can all go onto a IO extender (I2C or SPI). No need for CPU GPIO.
* Update to the current Stabilizer IO connector pinout.

**Comment by gkasprow** [comment]
@hartytp are you happy with two attenuators followed by ERA-2SM+ instead of PGA?

**Comment by hartytp** [comment]
I’m happy either way

**Comment by hartytp** [comment]
@dtcallcock should comment however

**Comment by dtcallcock** [comment]
I don't see a problem with this way of doing it.

**Comment by gkasprow** [comment]
@jordens I assume you don't plan to use hardware NSS pin because we will always transmit 48bits

**Comment by jordens** [comment]
On the attenuators?

**Comment by gkasprow** [comment]
yes

**Comment by jordens** [comment]
Yes. We can always load all attenuators. Here it's fine since it's easy to track the state either in software or by doing the non destructive procedure we have for urukul initialisation.

**Comment by jordens** [comment]
But why is it 6 attenuators?

**Comment by gkasprow** [comment]
We have two in output state and two cascaded instead of VGA, But I don't understand why we need to cascade two of them.

**Comment by hartytp** [comment]
I don't remember why we have two of them either. (I also can't remember why we decided to use the attenuator instead of the VGA)

**Comment by jordens** [comment]
I don't get why we need the VGA. The VGA gives you 2-18 dB gain, while using the existing step attenuator+gain block would give you -8 to 22 dB gain. And it has a 6 dB better noise figure!

**Comment by gkasprow** [comment]
To cover required -20..+10dBm range we would need to cascade two amplifiers to have 10dBm on the mixer input. I'm not sure we need that much because we can also increase the gain with opamp at the mixer output and work with let's say 0dBm.

**Comment by jordens** [comment]
Yes. Absolutely. The power at the mixer input only needs to be raised sufficiently to not matter for the noise. Going very high into the mixer (10 dBm) even for low input powers (-30 dBm) also kills the overall dynamic range. If we accept 10 dBm max input then with a 31.5 dB attenuator, 3 dB overall insertion losses, and a 24 dB gain block, we are at 0 dBm into the mixer and can maintain that 0 dBm level all the way down to -21 dBm RF input. Below that we start loosing performance, but probably only because of the noise figure of the input. Nothing a good external preamplifier and filter wouldn't solve. Above 10 dBm we would start clipping in the opamps which may also be fine since we tend to work in quadrature, i.e. at 0 V mixer output. Later the gain block would saturate before everything goes up in flames.

**Comment by hartytp** [comment]
> And it has a 6 dB better noise figure!

At low power levels. Obviously the NF is worse than -30dB at max power.

**Comment by gkasprow** [comment]
to use a single-stage gain block after the attenuator, we can go for one of them
[TSS-13HLN+](https://www.minicircuits.com/WebStore/dashboard.html?model=TSS-13HLN%2B) It  has NF=1.4 but costs 10.7$
Popular old [MAR-8A+](https://www.minicircuits.com/WebStore/dashboard.html?model=MAR-8A%2B) is just 1.5$ but has NF=3.1

**Comment by jordens** [comment]
No point in trying to beat the transformer+attenuator insertion loss with an expensive amplifer afterwards. ERA-3 or MAR-8 is all fine. MAR-8 might be preferable because it moves the input range down.

**Comment by jordens** [comment]
> At low power levels. Obviously the NF is worse than -30dB at max power.

More like 20 dB if you allow more power at the mixer.
But does that matter?

**Comment by hartytp** [comment]
> But does that matter?

Likely not in most cases.

**Comment by gkasprow** [comment]
So, what's the conclusion? Does such a solution work for all?
![obraz](https://user-images.githubusercontent.com/4325054/69952048-afabbe80-14f6-11ea-8685-a05a540aec4f.png)

**Comment by gkasprow** [comment]
edit, power levels were wrong

**Comment by gkasprow** [comment]
If the gain of MAR8 is too high, it can be easily replaced with ERA2. It has the same footprint and bias current. Gain gets reduced from 31 dB to 16dB

**Comment by hartytp** [comment]
@gkasprow does altium give one a nice way of swapping MAR8 FOR ERA2 in the BOM as a variant without having to have both on the schematic?

**Comment by gkasprow** [comment]
Yes, but it must have the same footprint and come from the same library. 
Old Altium could only add alternate value, the new AD can define component replacement.
variant1
![obraz](https://user-images.githubusercontent.com/4325054/69954325-542fff80-14fb-11ea-9102-7b805a07c46e.png)
Variant2
![obraz](https://user-images.githubusercontent.com/4325054/69954340-5befa400-14fb-11ea-8f50-89db722baf85.png)

**Comment by hartytp** [comment]
Aah, cool!

The reason I ask is that I'm thinking about making a high-frequency  (up to around 4GHz) version of Pounder with PLLs instead of DDSs. I assume this will be a new project that starts as a copy of Pounder, but was curious how much I might be able to do as a straight up variant...

**Comment by gkasprow** [comment]
We still have some board area, but it would be probably easier to do as a separate project. Production would need to be done as a separate process anyway. Variant routing of 4GHz signal and shielding could be tricky.

**Comment by gkasprow** [comment]
@hartytp do you want to make it like a dual-channel design?
If the rest remains the same, we can place synthesizer in the area under the shield in the rear board area
![obraz](https://user-images.githubusercontent.com/4325054/69957022-feab2100-1501-11ea-9d6d-0139cb8c5d54.png)
to support two channels, would you need two synthesizers?

**Comment by hartytp** [comment]
I'm not overly fussed about one channel v 2. It probably makes sense to keep it as a new design since there will be a lot of changes (baluns, filters, mixer) and I'm not sure we'll be able to make everything FP compatible.
