### ISSUE TITLE
bi-dir coupler

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#16]
Why are you using a bi-directional coupler instead of a 3-port directional coupler when you only need a forward power measurement? I've found the three port devices (with internal termination) tend to work better.

**Comment by dnadlinger** [comment]
This is probably the one coupler Mini-Circuits has that goes all the way down to 1 MHz. Just building a simple tap from discretes might be the way to go, though.

**Comment by gkasprow** [comment]
we can also go for [RDBC-20-63+](https://www.minicircuits.com/pdfs/RBDC-20-63+.pdf) which works from DC.
But can also be realized in the same way using just one resistor :)
The only coupler from Minicircuits that works from 1MHz is the one I used.

**Comment by jordens** [comment]
You can't have both low frequencies and directionality. If you ensure a good match and isolation after/by the amplifier than then a tap is fine.

**Comment by gkasprow** [comment]
well, you can build [directional coupler](http://michaelgellis.tripod.com/Bi-directional_amp.pdf) using opamps that work from DC :)
However, in our case we need to isolate LO leaking to RF input so existing solution may be optimal.

**Comment by jordens** [comment]
Yeah. I thought I had restricted that statement to passive.

**Comment by jordens** [comment]
The amplifier is pretty directional. You could put the tap between the step attenuator and the amplifier.

**Comment by gkasprow** [comment]
True, providing that we go for this option instead of PGIA.

**Comment by gkasprow** [comment]
I added 450R in series with power detector. This will give 10x attenuation
