### ISSUE TITLE
document input power levels

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#18]
It would be great to document (on the top page ideally) the RF input power level required to lightly (P1dB) saturate the input mixer with min/max PGA gain.

**Comment by hartytp** [comment]
More a software point than a hw point, but it would also be great to have LEDs to indicate low/high power levels.

**Comment by dtcallcock** [comment]
Also required input power level on ext_clk.

**Comment by gkasprow** [comment]
There are 6  front panel green LEDs connected to the I2C expander

**Comment by gkasprow** [comment]
Do we really need a double attenuator in front of ERA-2SM amplifier that drives the mixer?
with single attenuator, we accept -5.5dBm....+25.5dBm power level while driving the amplifier close to IP1.

**Comment by hartytp** [comment]
I assumed we’d want the gain/attenuation setup to be more in the range -30dBm to 0dBm but @dtcallcock / @dnadlinger should comment on the desired range

**Comment by gkasprow** [comment]
we would have to use an amplifier with much higher gain.
Single attenuator already has such gain window.

**Comment by hartytp** [comment]
Indeed. I don’t think two attenuators is a good idea

We also need to be careful over attenuating too much in order to avoid noise issues with attenuate/gain cascades

**Comment by hartytp** [comment]
I guess that’s the advantage of the vga... still, depends on what noise level people are looking to achieve here

**Comment by dnadlinger** [comment]
-30dBm to 0dBm or -20dBm to 10dBm sounds more like it, yes.

**Comment by gkasprow** [comment]
So, we definitely need to go for VGA. Otherwise we would need attenuator + dual stage amplifier

**Comment by gkasprow** [comment]
The VGA gives only 2dB to 18dB Gain Range. Optimally we would need attenuator and then VGA, but this would add one RF transformer that isolates the input.
We can also place the attenuator after the VGA. The VGA should handle 10dBm of input signal (IIP3 is 27dBm).

**Comment by hartytp** [comment]
If we need that much dynamic range vga followed by attenuator and fixed gain amp sounds good. 10dBm max input sounds fine

**Comment by jordens** [comment]
I don't think we need that much dynamic range. A step attenuator gives us 31.5 dB dynamic range already. Apart from needing one more transformer, the VGA has a pretty disappointing noise figure and less dynamic range compared to step attenuator plus era-3. And we can't reuse the software architecture that we need for the other step attenuators.

**Comment by hartytp** [comment]
Summarising this issue:
- [ ] @dtcallcock can you specify which max/min input power you want to support
- [ ] document this choice on the schematic
- [ ] design the attenuator/amplifier combo as well as the output buffer amp gain around this choice

**Comment by dtcallcock** [comment]
I thought we were happy with the design @gkasprow laid out in #13 

![obraz](https://user-images.githubusercontent.com/4325054/69952190-f3062d00-14f6-11ea-83dc-2f87c5967914.png)

**Comment by hartytp** [comment]
@dtcallcock okay, so you're happy with +12dBm being the max input, meaning drives the mixer at roughly its ~P1dB and gives approx +-1V at the Sampler input?

If so, @gkasprow are you happy that the amp isn't saturated, the mixer is driven appropriately and the filter gain is set correctly (and that this is all documented)?

If so, let's close.

**Comment by dtcallcock** [comment]
Works for me.

On Dec 29, 2019, at 12:13, hartytp <notifications@github.com> wrote:

﻿

@dtcallcock<https://urldefense.com/v3/__https://github.com/dtcallcock__;!!C5qS4YX3!XJtI20KiljbKAAEYT-l2bDaEaK3zKUPPffZBWK361mLdkMJmt0uA5R4JtVwb7RQP-I0$> okay, so you're happy with +12dBm being the max input, meaning drives the mixer at roughly its ~P1dB and gives approx +-1V at the Sampler input?

If so, @gkasprow<https://urldefense.com/v3/__https://github.com/gkasprow__;!!C5qS4YX3!XJtI20KiljbKAAEYT-l2bDaEaK3zKUPPffZBWK361mLdkMJmt0uA5R4JtVwbU9gU52Q$> are you happy that the amp isn't saturated, the mixer is driven appropriately and the filter gain is set correctly (and that this is all documented)?

If so, let's close.
