### ISSUE TITLE
power budget

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#23]
definitely needed since this AFE will burn non-negligible power

**Comment by gkasprow** [comment]
The power budget is here
[Phaser_Power_Pounder.xlsx](https://github.com/sinara-hw/Pounder/files/3907667/Phaser_Power_Pounder.xlsx)
The module will consume roughly 5.2W of power

**Comment by gkasprow** [comment]
The power budget includes dual attenuator and amplifier variant.

**Comment by gkasprow** [comment]
Updated power budget
[Phaser_Power_Pounder.xlsx](https://github.com/sinara-hw/Pounder/files/4008355/Phaser_Power_Pounder.xlsx)
