### ISSUE TITLE
power amp

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#24]
Do we really need the power amp? Is this a niche use-case better served by a packaged amp near the load?

If we do need it, someone needs to check the design carefully. Power levels appropriate, power handling of switches etc, thermal management, etc. Also make sure the PA is powered down by default. Maybe have an LED to indicate when it's active?

**Comment by hartytp** [comment]
NB any coupling between the RF output and input can give offsets on the lock signal. Since we have a lot of gain here, we'll have to be very careful about decoupling the two halves of the circuit.

**Comment by gkasprow** [comment]
Shall I add a shielded cage for Rx part?

**Comment by dnadlinger** [comment]
I've opened #27 regarding shielding.

**Comment by dtcallcock** [comment]
Ok, let's scrap this.

**Comment by gkasprow** [comment]
I removed the power amp. it is still on the schematics but disabled with compile mask so you can still change your mind
