### ISSUE TITLE
test points, LEDs, 0R etc

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#25]
Please can we have lots of LEDs: all power lines, lock detect signals, front plane, etc

Also, lots of test points, covering all useful signals (inc SPI, I2C, power lines, etc). 

I also find it useful to have a smattering of 0R resistors to make it easier to disconnect parts of the circuit during debugging (e.g. on digital lines, RF lines, etc).

**Comment by dtcallcock** [comment]
Some of the testpoints and power LEDs got dropped when copying the power rail stuff over from Urukul.

**Comment by gkasprow** [comment]
added testpoints, 0R on RF lines, LEDs for all rails.
