### ISSUE TITLE
Mixer IF load

### ISSUE THREAD

**Issue by dnadlinger** [sinara-hw/Pounder#28]
The mixer IF output is currently 50Ω-terminated at AC, with a corner frequency of ~ 1 kHz, and 4.7kΩ at DC:

<img width="537" alt="Screenshot 2019-10-06 at 5 18 39 PM" src="https://user-images.githubusercontent.com/19335/66272103-63793080-e85d-11e9-9d2b-13142cd84911.png">

I guess this might have been a misunderstanding based on the diplexed setup I had suggested elsewhere for optimising the voltage/phase slope at DC (for which a more appropriate corner frequency would be a MHz or so). 

Perhaps we should just go with a simple 50 Ω load by default, though, as this is definitely the most universal (if slightly suboptimal) option across all use cases, and should avoid confusion.

**Comment by dtcallcock** [comment]
The load @dnadlinger suggested from https://doi.org/10.1109/FCS.2011.5977868 was:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/20587606/66275369-cd351280-e83c-11e9-850d-e3ac48d3d0ff.png">

This is based on [this paper](https://doi.org/10.1109/FREQ.1977.200168) and [this one](https://arxiv.org/abs/physics/0608211).

**Comment by dtcallcock** [comment]
> Perhaps we should just go with a simple 50 Ω load by default

I think this is a reasonable approach. We should have the pads to allow people to realize the above topology though.

**Comment by dnadlinger** [comment]
@dtcallcock: Thanks for collecting the links. Yes, having the pads is probably a good idea. If we include two parallel pairs of pads for a series-Z connection to ground (like the RC in the above), people could also put on passive notch filters at f/2f like in the old PDH literature. (I've never tried to measure whether that's actually a good idea.)

**Comment by gkasprow** [comment]
I implemented 50R by default. The topology from the paper can be implemented as well.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/69905086-5e44e780-13af-11ea-8928-441739fb65c9.png)
