### ISSUE TITLE
ERA2SM (LO amp)

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#31]
-At <200MHz the gain of the ERA2SM is typically 16dB, not 15dB.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/20587606/66278045-7a6a5380-e85a-11e9-8963-6c71ef7dd863.png">

Should we change 9dB pad (IC23) before to a 10dB pad to maintain 11dB into mixer and fix the annotations?

**Comment by dtcallcock** [comment]
The bias resistor should be 88.7R if you're using E96.

**Comment by dtcallcock** [comment]
> Should we change 9dB pad (IC23) before to a 10dB pad

I mean change from 1dB to 2dB.  The confusion was because the symbol sayd '9dB' on it for some reason.  This is a problem with both IC23 and IC17.

**Comment by gkasprow** [comment]
changed to 2dB
