### ISSUE TITLE
ERA3SM (output amp)

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#33]
- Power annotation just before amp is wrong (should be -15dBm).
- We are using 100R to bias but [datasheet](https://www.minicircuits.com/pdfs/ERA-3SM+.pdf) suggests 107R as optimum for 7V operation.

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/69901995-05625880-1389-11ea-8953-b6068c23b889.png)

**Comment by gkasprow** [comment]
@dtcallcock there was misleading "9dB" text on the 1dB attenuator symbol.
So we have -5dBm power level. Together with 23dB of gain it gives 13 dBm at the output. So T pad should have 4dB so we get 13dBm at the ERA-3SM+ output.

**Comment by gkasprow** [comment]
We can connect two 2dB attenuators to save one BOM line.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/69903538-f5ec0b00-139a-11ea-8191-b3d87945a4d7.png)

**Comment by gkasprow** [comment]
since we decided to scrap power amp, this is not an issue anymore
