### ISSUE TITLE
Front panel

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#34]
Currently:

- 2x SMA in
- 2x SMA out
- 1x SMA ext CLK in

How about adding: 

- 2x CPU ADCs (unused JADC5 P & N) to MCX for monitoring photodiodes (for example the NIST doublers have a built-in photodiode that monitors the output power)?
- Some user LEDs (if we have any spare IO from CPU or extenders)?

**Comment by dtcallcock** [comment]
>Some user LEDs

From: https://github.com/sinara-hw/Pounder/issues/18#issuecomment-536330465

> it would also be great to have LEDs to indicate low/high power levels.

**Comment by dtcallcock** [comment]
Right now there is a barrel connector (J6) on the schematic and a Molex connector on the back.  Are these for if the [power budget](https://github.com/sinara-hw/Pounder/issues/23) exceeds what Stabilizer can supply?

**Comment by hartytp** [comment]
The barrel connector is useful IMHO because we couldn’t fit one on the stabilizer FP and one doesn’t always want to use PoE 

Not sure I see any use for the rear molex since stabilizer has one already

**Comment by dtcallcock** [comment]
So this would essentially be the same front panel as Stabilizer but with the ethernet+usb replaced by power barrel + ext_clk SMA.  Looks a bit tight but I'm happy with that if it can be made to work.

**Comment by jordens** [comment]
Adding a barrel connector to the 5 SMA would be painful. If you put these in a rack and don't want to use PoE, can't people just wire up the Stabilizer power input in the crate? Or use VHDCI Carrier to power many Stabilizer If that's the goal. If they are not in a rack but in a separate enclosure, the back connector would stick out anyway and be easily accessible.

**Comment by gkasprow** [comment]
two MCX is not a problem. Route it directly to the CPU ADC? These are 0-2V048 inputs. 
more LEDs are also OK, I need I2C expanders anyway
