### ISSUE TITLE
Ext Clk transformer

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#35]
Isolation transformer [T2-1T](https://www.minicircuits.com/pdfs/T2-1T.pdf) only goes to 200MHz.  We want to be able to drive this at 500MHz to avoid using the DDS internal multiplier.  

It looks like [ADT2-1T-1P+](https://www.minicircuits.com/pdfs/ADT2-1T-1P+.pdf) will do the job.

Should also check the following 100nF caps (C105 & C195) behave reasonably at 500MHz.

**Comment by gkasprow** [comment]
done. I changed the termination resistor to  100R.
Capacitor Z at 500MHz is [0.8R](https://ds.murata.co.jp/simsurfing/mlcc.html?partnumbers=%5B%22GRM155R61C104KA88%22%5D&oripartnumbers=%5B%22GRM155R61C104KA88D%22%5D&rgear=jomoqke&rgearinfo=com)
