### ISSUE TITLE
DDS decoupling caps

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#38]
On the [eval board](https://www.analog.com/media/en/technical-documentation/evaluation-documentation/57418637811849AD9959_pcb_0.pdf) there is a 10uF as well as 2x 100nF for each power (AVDD0, AVDD1, AVDD2, AVDD3, CLK_VDD, DVDD, DVDD_IO).  Should we beef up our decoupling to match?

**Comment by gkasprow** [comment]
OK, done
