### ISSUE TITLE
DDS loop filter

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#39]
Schematic matches [eval board](https://www.analog.com/media/en/technical-documentation/evaluation-documentation/57418637811849AD9959_pcb_0.pdf) with 698R in series with 680pF to GND.  This seems wise.

[Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/AD9959.pdf) though says "Typically, the network consists of a 0 Ω resistor in series with a 680 pF capacitor tied to AVDD."  Should we add non-populated capacitor pad to AVDD in case we find it better to follow the datasheet recommendation?

**Comment by gkasprow** [comment]
I assume it should be connected to CLK_VDD. We don't have AVDD anymore since I splitted the power rails.
