### ISSUE TITLE
DDS output filter

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#40]
Right now specified as DC to 160MHz.

Presumably this is an [LFCN-160](https://www.minicircuits.com/pdfs/LFCN-160+.pdf)?

<img width="311" alt="image" src="https://user-images.githubusercontent.com/20587606/66367578-9993de80-e949-11e9-89e7-5b110d7a7706.png">

An alternative part would be [ULP-216+](https://www.minicircuits.com/pdfs/ULP-216+.pdf).

<img width="223" alt="image" src="https://user-images.githubusercontent.com/20587606/66368093-c6e18c00-e94b-11e9-89bd-5649f593dad2.png">

Would give the same bandwidth but quite a bit better attenuation of the image frequencies.  More expensive and much larger footprint though so perhaps not worth it.

**Comment by jordens** [comment]
Not worth it IMO. Have the user clean inputs and outputs with custom bandpasses if there is are problems with aliases.

**Comment by gkasprow** [comment]
Yes, it is LFCN-160+ now. Before there was just a placeholder.
