### ISSUE TITLE
annotate power levels

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#49]
Please can we have clear annotations on the schematic top page for the input/output power ranges?

**Comment by hartytp** [comment]
also annotation clock input power range (NB it's only a 1V8 supply so can't take that much power)

**Comment by gkasprow** [comment]
done.

**Comment by hartytp** [comment]
The annotation says the clock inputs can take 2.5Vpp. Isn't that a little high? Or is the balun loss really that bad?
