### ISSUE TITLE
fancy capacitors

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#50]
didn't we agree not to use fancy rf caps?

**Comment by gkasprow** [comment]
Well, my understanding was that we need to use them to avoid assembly variants.

**Comment by gkasprow** [comment]
Is there anything to fix? Can we go for production

**Comment by hartytp** [comment]
@gkasprow can you post an updated schematic with all fixes implement so we can all sign off?

**Comment by gkasprow** [comment]
[done](https://github.com/sinara-hw/Pounder/releases/tag/v1.0rc1)
