### ISSUE TITLE
input LPF

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#53]
Let's populate C60A by default to give a sensible LPF response. @dtcallcock any preference as to cut-off frequency?

**Comment by gkasprow** [comment]
done

**Comment by dtcallcock** [comment]
Probably something that's comfortably above the 500kHz LPF response of the Stabilizer servo.

What did you go for @gkasprow ?

**Comment by gkasprow** [comment]
At the moment there are 9k1 and 180pF.
I can change it to 33p to get 530k

**Comment by dtcallcock** [comment]
Sounds reasonable.  It's an 0805 package, so easy to change right?

**Comment by gkasprow** [comment]
0603

**Comment by dtcallcock** [comment]
Good enough.

**Comment by gkasprow** [comment]
All  filter components are 0603, only bigger caps are 0805 to keep them C0G
