### ISSUE TITLE
SYNC in

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#55]
Should this be driven by an external source? Is it useful to have it driven by stabilizer?

**Comment by hartytp** [comment]
do we want to break out SYNC_OUT to a DNPd MMCX?

**Comment by gkasprow** [comment]
done
I added DNP IN and OUT. No idea if it is useful to drive it from CPU
![obraz](https://user-images.githubusercontent.com/4325054/71624394-96c02700-2be2-11ea-89f7-47ef9d577dd0.png)

**Comment by jordens** [comment]
SYNC_IN/OUT to Stabilizer is of limited usefulness since referencing Stabilizer externally is mostly unexplored. MMCX for SYNC_IN is good.
