### ISSUE TITLE
loop filter

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#56]
why do the DDS loop filter default population options not follow the eval board?

**Comment by gkasprow** [comment]
well, it does
![obraz](https://user-images.githubusercontent.com/4325054/71624167-80fe3200-2be1-11ea-9bed-301d79fdb0e2.png)
![obraz](https://user-images.githubusercontent.com/4325054/71624173-878ca980-2be1-11ea-8f99-ffcd05ac4a28.png)

**Comment by hartytp** [comment]
Iirc the eval design connects the cap to a vcc

**Comment by gkasprow** [comment]
Here is [a schematic ](https://www.analog.com/media/en/technical-documentation/evaluation-documentation/57418637811849AD9959_pcb_0.pdf)of eval board. The drawing above was copied from that pdf file.

**Comment by hartytp** [comment]
hmmm...I was looking here https://www.analog.com/media/en/technical-documentation/evaluation-documentation/ad9958-ad9959-schematic.pdf

![image](https://user-images.githubusercontent.com/21218399/71626284-506bc780-2be4-11ea-9a8a-cd217c1fa807.png)

**Comment by gkasprow** [comment]
OK, let's connect it to CLK_VDD then.

**Comment by hartytp** [comment]
Okay, so there are two inconsistent versions of the schematic linked to from https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/eval-ad9959.html#eb-documentation

The one I posted matches the pin description 
![image](https://user-images.githubusercontent.com/21218399/71631719-1e695e00-2c02-11ea-98a4-3aa315908bd6.png)

Also, IIRC it's more normal to decouple the CP output to Vcc than to GND so it makes more sense that way.

Maybe the schematic in the eval board data sheet is out of date?

**Comment by hartytp** [comment]
If we're going to follow the eval board/pin description, shouldn't the resistors be 0R?

**Comment by gkasprow** [comment]
OK, let's make it 0R
![obraz](https://user-images.githubusercontent.com/4325054/72474292-c37e5c00-37e8-11ea-9c19-a60a769e6809.png)
