### ISSUE TITLE
dds supply decoupling

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#57]
are we happy running the DDS analog and digital supplies from the same LDO with only a FB to decouple? I didn't see a clear recommendation on this. Feel free to close this issue if you're happy with the current situation @gkasprow

**Comment by gkasprow** [comment]
The EVKIT has separate supply terminals for digital and analog lines.
I added more aggressive LC circuit for digital rails. I will replace the FB with regular 4.7uH, 17mOhm inductors
