### ISSUE TITLE
TCM2/PWDN

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#58]
Should we drive this pin? At least let's have a DNPd divider between Vcc and GND...

**Comment by gkasprow** [comment]
I added compensation resistors as recommended in DS
![obraz](https://user-images.githubusercontent.com/4325054/71623255-80fb3380-2bdb-11ea-93ca-6fcc5fa595d1.png)

**Comment by hartytp** [comment]
Nitpick: why the pink highlighting in the screen clip?
