### ISSUE TITLE
detector filter capacitors

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#59]
@dtcallcock are you happy the power detector capacitor values are suitable for the frequency range you want to cover? What about the Vref etc?

**Comment by dtcallcock** [comment]
> power detector capacitor values are suitable for the frequency range you want to cover?

They seem to match up with datasheet recommendations.

> What about the Vref etc?

Do you mean the fact that Vref is not connected to TCM1 or TCM2?  The datasheet seems to imply in some places that connecting TCM1/TCM2 to a specific voltage is optional but doesn't say what you should do with them (ie. leave floating?) or what the implications are.  I'd be tempted to add an unpopulated potential divider between Vref and GND for each as risk mitigation.
