### ISSUE TITLE
P/N 5V LDO lockup prevention diodes

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#60]
78/79 LDOs are prone to lockup when used with high Iq OpAmps.

- [x] while we're at it, should they have a 10uF tantalum output capacitor?

**Comment by gkasprow** [comment]
The datasheet says nothing about output caps. They only specify 0.1uF. The caps cannot have too low ESR. 78/79 will for sure oscillate with too high capacitances with low ESR, for example, 4.7u X7R. I can add high ESR tantalum, but I'm not sure they are needed.
I added the diodes.
![obraz](https://user-images.githubusercontent.com/4325054/71622923-6627bf80-2bd9-11ea-9814-865f3be629a3.png)
