### ISSUE TITLE
run PI sim

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#63]
(if only to check power margin on LDOs etc)

**Comment by gkasprow** [comment]
Setting up the PI analysis takes a few hours of work so I do it only for complex circuits or critical rails. Here, we are copying power supply from already tested designs. I don't think it is necessary in this case.

**Comment by hartytp** [comment]
Ok fair enough

Please can you 
- [ ] add a power budget to the schematic
- [ ] confirm that no rail exceeds its max current 

Then we can close

**Comment by hartytp** [comment]
The power budget says that the 5V0A rail can draw up to 145mA, but the LT1761 is only a 100mA regulator...replace with a 3045 (thereby removing a BOM line)?

**Comment by hartytp** [comment]
All other rails look fine (we're generally using 3A LDOs for rails drawing 100mA or so!).

**Comment by hartytp** [comment]
NB if we add a new pre-amp we'll need to check the power budget on that rail...

**Comment by gkasprow** [comment]
good catch. Fixed
![obraz](https://user-images.githubusercontent.com/4325054/72473072-2e7a6380-37e6-11ea-92af-8266af637126.png)

**Comment by hartytp** [comment]
Did you mean to connect pins 1 and 2?

**Comment by gkasprow** [comment]
I did it already.
