### ISSUE TITLE
OSC1 tuning

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#65]
Add a testpoint to OSC1 pin1 and a DNP 0R jumper plus two stage 10 kHz RC lowpass components to connect to DAC_O1_OUT1 from Stabilizer. And make R167/R168 a solderable ~0603 size.

![image](https://user-images.githubusercontent.com/1338946/71624888-236be480-2be5-11ea-8fe2-a9ac763e225f.png)

**Comment by gkasprow** [comment]
added
![obraz](https://user-images.githubusercontent.com/4325054/71625472-4ba91280-2be8-11ea-93f4-a33c9bfdef35.png)

**Comment by hartytp** [comment]
Nitpick, but would it be better to move the tp to the other side of R73 (close to the osc pin)?
