### ISSUE TITLE
rc2

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#69]
Completed my review of rc2. Looks good!

#63 needs to be resolved. The other open issues are non-critical as far as I'm concerned...

**Comment by dtcallcock** [comment]
Annotation at C82 is -16dBm.  Should be -26dBm.

**Comment by dtcallcock** [comment]
Should there be some cool logos on the board?

Other than that, I also think it looks great.

**Comment by dhslichter** [comment]
![image](https://user-images.githubusercontent.com/9222487/72190673-67b56c80-33bd-11ea-94b4-99f8b7297211.png)

**Comment by dhslichter** [comment]
Make some line art of this guy.  He'd be pleased to be on the board :)

**Comment by gkasprow** [comment]
is that OK?
![obraz](https://user-images.githubusercontent.com/4325054/72476455-91bbc400-37ed-11ea-86b0-42831d3ed69d.png)

**Comment by hartytp** [comment]
@gkasprow did you really take @dhslichter's comment seriously???? Can we scrap that plz?

On a more important note, I've seen jumpers like this lead to GHz-frequency oscillations before due to added input-output coupling
![image](https://user-images.githubusercontent.com/21218399/72594811-4e9e4580-3900-11ea-8d69-c0e84f81558b.png)

**Comment by gkasprow** [comment]
Did U see the physical layout?
I can use bigger footprint that woulf not change amplifier pads distance. We can also scrap it. I thought that you dont need this amp.

Pozdrawiam,
G.Kasprowicz

________________________________

**Comment by hartytp** [comment]
> Did U see the physical layout?

No. I don't have altium right now and you didn't include the layout in the pdf. If you're happy with this then it's fine by me.

> I thought that you dont need this amp.

We will want this amp for pounder (not for phaser, because it's a different application in our lab).
