### ISSUE TITLE
TCM Input impedances

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#70]
>The TCM1 and TCM2 pins have high input impedances, approximately 5 kΩ and 500 kΩ, respectively

But actually TCM1's 5k is not high compared to R59/R61.

How about using R59 = 9.76k, R61=4.99k?  Though probably don't need E96 precision given the 'approx' in front to the 5k pin impedance.

R66 could be changed to 31.6k to compensate for TCM2 impedance.

**Comment by gkasprow** [comment]
Vref can source up to 4mA, so we can lower the dividers 10x
![obraz](https://user-images.githubusercontent.com/4325054/72476931-c1b79700-37ee-11ea-8ab4-096a20a30ea5.png)
