### ISSUE TITLE
Shielding Can

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Pounder#71]
I'm not sure the current shielding cans are optimal.  The main problem with PDH locks in output->input crosstalk.  Therefore to be useful I think they should cover the input only.  This is also the part of the circuit most sensitive to pickup. 

If it's a big job to alter we can always make measurements on v1.0 to see if it's worth the effort.

**Comment by gkasprow** [comment]
It would be a lot of work to cover only Rx part. Especially when I added the PWR amp.
What I can quickly do is to move the Rx parts to the bottom layer, especially Rx transformer and PWR stage that can generate EMI

**Comment by dtcallcock** [comment]
To be clear, you mean move this stuff to the other side of the PCB?

![image](https://user-images.githubusercontent.com/20587606/72477765-20582300-37a5-11ea-8c8e-5ccf6572fe8e.png)

**Comment by gkasprow** [comment]
no, just PWR amp and balun. They are close to the input

**Comment by gkasprow** [comment]
ICs don't generate much coupling

**Comment by dtcallcock** [comment]
Sounds like a reasonable compromise.

**Comment by gkasprow** [comment]
I drafted the new release. I think it can go to production.

**Comment by gkasprow** [comment]
How many pcs shall we produce?

**Comment by dtcallcock** [comment]
> I drafted the new release. I think it can go to production.

Sounds good to me.

> How many pcs shall we produce?

I'd say 3 is a minimum.  @jordens will need one for gateware development, and then us and Oxford would want one each for testing (assuming @dnadlinger or @hartytp is interested in having a play).  Probably all 3 should go to @jordens to start with in case there is a bad board.  

Whether you should make a few more on top of that depends on the price breaks you get for runs of this size.

**Comment by dtcallcock** [comment]
Related: @jordens do you have Stabilizer v1.1 hardware available or do you need me to ship you one?

**Comment by jordens** [comment]
I'm not going to rework boards.

**Comment by jordens** [comment]
@dtcallcock I have a stabilizer 1.1. Can you port the current firmware to it?

**Comment by dtcallcock** [comment]
> I'm not going to rework boards.

Exactly.  If you have more than one board you can put a bad board aside and use a different one instead of reworking\debugging the bad one.

**Comment by dtcallcock** [comment]
> Can you port the current firmware to it?

No, I don't have anyone with those skills in my group yet.  How much work is involved?

**Comment by jordens** [comment]
In the past the prototype fabrication has been consistent. It makes more sense to hold two boards at the Fab for possible reworks.

**Comment by dtcallcock** [comment]
> It makes more sense to hold two boards at the Fab for possible reworks.

Then let's do that.

**Comment by jordens** [comment]
@dtcallcock see quartiq/stabilizer#66
