### ISSUE TITLE
output amp bias

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Pounder#73]
why does this have different bias resistors to the other ERA?

![image](https://user-images.githubusercontent.com/21218399/72594662-d59eee00-38ff-11ea-94c0-7b560c84bf20.png)

**Comment by hartytp** [comment]
![image](https://user-images.githubusercontent.com/21218399/72594682-e5b6cd80-38ff-11ea-82b1-50056dd6838b.png)

**Comment by gkasprow** [comment]
fixed
