### ISSUE TITLE
PTH Hole broken

### ISSUE THREAD

**Issue by psyryczyk** [sinara-hw/Pounder#75]
The PTH hole intersects the outline. This hole will be broken and exposed copper when milling.

![PCB outline on PTH](https://user-images.githubusercontent.com/26919830/73874919-a6bbce00-4854-11ea-8ecc-0ae0bbef238b.png)

**Comment by gkasprow** [comment]
fixed
![obraz](https://user-images.githubusercontent.com/4325054/105580229-61f1b580-5d8b-11eb-9d06-d35e817546b8.png)
