### ISSUE TITLE
SYNC_CLK to Stabilizer ETR/CHx timer input

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#76]
* I don't see how SYNC_IN is useful. Should have done thorough analysis in #55 
* We should enable SYNC_OUT to the CPU for accurate software-demodulation (required for quartiq/stabilizer#80)
* This needs a timer channel input with external clocking capability to be used as counter
* Counting 125 MHz may or may not be doable with the stm32h7 (but should be checked) physically.
* Potentially interesting input topologies would be: TIMx_CHx or maybe better TIMx_ETR+internal asynchronous ETPS prescaler (/4 or /8)?
* From what I can tell it's not possible with the HRTIM. It would need to be a general purpose or advanced timer. Maybe HRTIM_EEVx though?
* If 125 MHz is too fast for a timer, the alternatives are (a) a discrete prescaler or (b) using one of the the reference clock outputs from Pounder (10 MHz from SMA only then) to a timer channel counter input on Stabilizer
* If prescaler, then consider possible prescaler phase measurement and compensation (deterministic closed loop phase)
* Better to use SYNC_CLK than SYNC_OUT b/c duty cycle?

**Comment by gkasprow** [comment]
@jordens I plan a new release of Stabilizer. Which solution would be the most promising? An LVCMOS divider /8 would be fine?
Of course, I would have to change in Stabilizer design the IO pin assigned to this particular GPIO header pin. I can add such circuit to existing boards - I have one Stabilizer and one Pounder.
What do you mean by prescaler phase measurement and compensation? D you mean IC propagation delay? Why would we care about it since the STM32 input is not compensated.

**Comment by jordens** [comment]
We use PA0 for DDS_RESET on Pounder v1.0. After we checked the max input frequency on PA0, I'd suggest connecting DDS_RESET to J10:11 (PG6) and SYNC_CLK (if needed through a /8 prescaler) to J10:18 (PA0). And on Stabilizer the PA0 wire should be cleaned up to and there should probably be some termination (series or AC parallel?).

**Comment by gkasprow** [comment]
It's easier for me to add a prescaller and bypass option than to check max STM frequency, especially if it is undocumented and may not work with other production batches.

**Comment by gkasprow** [comment]
@jordens I cleaned the PA0, the next action is to modify the pounder, right?

**Comment by jordens** [comment]
Yes

**Comment by jordens** [comment]
I checked the counter input. No external prescaler needed. Just

* connect DDS_RESET to J10:11 (PG6)
* connect SYNC_CLK to J10:18 (PA0) make sure that this 125 MHz signal gets to the CPU with correct level and decent termination/matching

**Comment by ryan-summers** [comment]
The changes @jordens proposed above were manually completed by me on TS 38/20 0002. In addition to the changes mentioned above, I also removed R70 (to disconnect SYNC_IN from PA0).

I have run firmware and verified that the clock can be properly driven using this hardware configuration and this is sufficient for timestamping ADC samples.
