### ISSUE TITLE
IF amp oscillating

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#79]
@gkasprow you [mentioned](https://github.com/sinara-hw/Pounder/issues/19#issuecomment-569631706) the THS4631 is weird.
It oscillates when the IF gets to -0.4 V (at the output, G=3). A couple pF negative feedback fix it.

![image](https://user-images.githubusercontent.com/1338946/81965840-eb57c200-9618-11ea-9306-579608286c12.png)

**Comment by gkasprow** [comment]
The THS4631 input is weird. You cannot make classical integrator out of it for example due to strange non-lineairty.

**Comment by gkasprow** [comment]
I added 4.7pF mounted by default

**Comment by gkasprow** [comment]
There is new fast JFET opamp which behaaves as expected - it's OPA818

**Comment by jordens** [comment]
THS4631DGN is still in the schematic v1.1rc1. don't you want to use the opa818?

**Comment by gkasprow** [comment]
It has a completely incompatible footprint. I can add it as an assembly option and populate it by default.

**Comment by jordens** [comment]
Maybe there are footprint compatible alternatives? The oscillation is really a functional problem. Or can we change the feedback to reliably prevent it?

**Comment by gkasprow** [comment]
OPA657, AD8065

**Comment by jordens** [comment]
AD8065 for lower power. I don't need offset stability or robustness against RF rectification. Can you add 100 or 1k series protection to ADC_[01]_P? The 50R termination would otherwise exceed abs max rating.

**Comment by jordens** [comment]
Let's go for the AD8065.

**Comment by gkasprow** [comment]
ok, done
added 50R resistors and replaced an opamp
