### ISSUE TITLE
v1.1 changelog

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Pounder#86]
- aligned SMA connectors #80 
- added 22uF at the LDO outputs #77 
- moved PCB edge #75 
- fixed PN in 47k resistor #83 
- R134, R166 changed to 0402 to lower the BOM count
- R136  -> 4k7 #82 
- added 4.7pF to the THS4631D #79 
- DDS_RESET connected to J10:11 (PG6) #76
 - SYNC_CLK connected to J10:18 (PA0) #76
 - removed SYNC_IN connection to CPU and R70 #76
 - THS4631 replaced by AD8065 #79 
 -  ADT1-1WT replaced by  TC1-1T 
 - added 50R resistors in series with CPU ADC inputs
 - making the RF amps DNP by default
-  swapped R15 with L85

**Comment by jordens** [comment]
Great. Could you spin the RC production files so we can give it a quick check?

**Comment by gkasprow** [comment]
[done](https://github.com/sinara-hw/Pounder/releases/tag/v1.1rc1)

**Comment by jordens** [comment]
I had a look at the changes. Apart from the opamp change #79 I'm ok with v1.2 and would like to proceed with getting it manufactured. As a note I still think that:

* The baluns should all become TC1-1T (replace 7 ADT1-1WT)
* The use of pricey "special RF" capacitors for DC-blocks at 1-200 MHz is not supported by data, evidence, or experience with the other dozen designs that don't have and don't seem to require them. When I look at standard MLCC for DC-blocking in 1-200 MHz, they are all just fine.
* Putting RF output and RF input signal paths into the same RF shield box makes the purpose and benefit of the boxes unclear to me: is it for emission or immission or crosstalk?
* The RF output amplifiers can go away.

But since this is all still experimental, I'm not going to fight these.

**Comment by jordens** [comment]
@gkasprow AFAICT there is only the opamp change (#79) pending for v1.2. Can we cut the release and send the production files?

**Comment by gkasprow** [comment]
> The baluns should all become TC1-1T (replace 7 ADT1-1WT)

Just to simplify the BOM?

>    The use of pricey "special RF" capacitors for DC-blocks at 1-200 MHz is not supported by data, evidence, or experience with the other dozen designs that don't have and don't seem to require them. When I look at standard MLCC for DC-blocking in 1-200 MHz, they are all just fine.

I was curious about real benefits. We can always use Hi-Q caps instead.


>    Putting RF output and RF input signal paths into the same RF shield box makes the purpose and benefit of the boxes unclear to me: is it for emission or immission or crosstalk?

Only output path attenuator was placed under the shield, the PA sits on the other PCB side. If we discover crosstalk, I will place the attenuator on the bottom PCB side


>    The RF output amplifiers can go away.

Why?

**Comment by jordens** [comment]
> Just to simplify the BOM?

BOM simplification, availability (the ADT1-1WT are quite a bit more exotic and hard to replace with anything footprint compatible, while the TC1-1T style is ubiquitous), and board space.

>  If we discover crosstalk

Right. We should measure crosstalk.

> The RF output amplifiers can go away.

They are typically not needed. Like for Urukul and Mirny, the usual amplifiers (e.g. Booster) would take 0 dBm (-5 dBm might be a little low however). And power usage: getting rid of them would reduce the power consumption by 0.7 W.

**Comment by gkasprow** [comment]
The amplifier can be bypassed by the assembly option. I will make the bypass default configuration.

**Comment by dtcallcock** [comment]
> They are typically not needed. 

Actually I find the -5 to 10dBm range is often what you need to add few percent sidebands with a modulator device/laser input, and having to add an external amp to achieve these very modest signal levels would be annoying.  But as long as it's retained as an option then that's fine.  

Noting on the schematic/wiki that an [ERA 50SM+](https://www.minicircuits.com/pdfs/ERA-50SM+.pdf) can be populated here instead would also be nice.  This extends the output to an even more useful +13dBm.  Sure it's another 280mW of power consumption but it's just a suggestion so nobody needs to compromise.

**Comment by gkasprow** [comment]
[v1.1 release is ready](https://github.com/sinara-hw/Pounder/releases/tag/v1.1rc2)

**Comment by gkasprow** [comment]
@kaolpr @akaminska

**Comment by jordens** [comment]
Thanks!

**Comment by dtcallcock** [comment]
![image](https://user-images.githubusercontent.com/20587606/106813045-591fa000-6625-11eb-938b-acb5d7eab73b.png)
Super minor, but can you make R34 the omitted component, not L15?  Any reasonable lab will have a kit with suitable resistors but the right inductor would probably have to be ordered.

**Comment by gkasprow** [comment]
the inductor will make a stub

**Comment by dtcallcock** [comment]
true dat

**Comment by gkasprow** [comment]
One would have to order the amplifier anyway :)

**Comment by dtcallcock** [comment]
Good point. Perhaps add the part number as a schematic annotation so one can order it without having to find an Altium licence though?

**Comment by dnadlinger** [comment]
Shouldn't we be able to just flip them around? A 82 Ohm resistor should be low-enough Q at our frequencies? Just asking out of curiosity.

**Comment by gkasprow** [comment]
yes, we can swap them. The resistor has smaller pads than the inductor so capacitance should be not an issue
![obraz](https://user-images.githubusercontent.com/4325054/110038980-cfa4e000-7d40-11eb-925e-c4c3d3efe4c0.png)
