### ISSUE TITLE
fix reference clock output label

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#88]
This is in fact a reference clock output. Let's label it "CLK OUT".
Also let's DNP it. The SMT MMCX are so easy to rip off and I'm not aware of a imminent and well-defined use case that would be able to use this clock.

![image](https://user-images.githubusercontent.com/1338946/105642037-6c917500-5e87-11eb-8927-8d09b1e985c5.png)

**Comment by gkasprow** [comment]
right!

**Comment by gkasprow** [comment]
done
