### ISSUE TITLE
trace impedance and separation

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#89]
The 50 Ohm signal traces seem to be really close to other traces, other pads, copper fill elements. Are the rules ok?

![image](https://user-images.githubusercontent.com/1338946/107794771-23cb2e80-6d58-11eb-82db-ed34de9489bf.png)
![image](https://user-images.githubusercontent.com/1338946/107795128-91775a80-6d58-11eb-9b0c-89de1cb8420e.png)
![image](https://user-images.githubusercontent.com/1338946/107795235-b23fb000-6d58-11eb-92ce-ee4e54513582.png)

**Comment by gkasprow** [comment]
it looks so.

**Comment by jordens** [comment]
Yes. Coupling to the GND plane below may dominate making this OK.
Let's leave it open as one item for characterization: crosstalk. If that turns out to be problematic, we can look at swapping of the in/out DDS channels (much more separated routing without layer crossing jumpers) and separated shielding cans.

![image](https://user-images.githubusercontent.com/1338946/107883929-3d07e280-6ef2-11eb-8c3c-ff03a272a86e.png)

**Comment by gkasprow** [comment]
I fixed the 3 first issues

**Comment by gkasprow** [comment]
I improved trace routing - added GND copper shielding
![image](https://user-images.githubusercontent.com/4325054/181731864-e3f5ff7d-02bd-40d0-8a69-bfa874ceef50.png)

**Comment by jordens** [comment]
Nice. Thanks.
