### ISSUE TITLE
DDS SPI: SI, digital -> analog crosstalk

### ISSUE THREAD

**Issue by dnadlinger** [sinara-hw/Pounder#9]
For PDH-type locks, the digital lines to the DDS(es) will mostly be quiet, but for fibre noise cancellation (#7), there will be continuous updates. We should be somewhat careful during layout to keep contamination to a minimum, particularly as one might end up with bus frequencies close to the RF/LO.

**Comment by dnadlinger** [comment]
(The signal integrity on those lines of course must also be good enough to support high-speed operation of the serial bus.)

**Comment by dtcallcock** [comment]
If Pounder is a Stabilizer AFE then this signal integrity requirement also applies to Stabilizer.

@gkasprow Do you think the GPIO header on Stabilizer is up to running a 100-200MHz SPI interface?

**Comment by gkasprow** [comment]
The GPIO header should not be an issue, I'm not sure about the CPU. I can make the SPI properly terminated 50Ohm (or 75 ohms) and increase the track clearance to support such a mode.

**Comment by gkasprow** [comment]
DDS schematic
![obraz](https://user-images.githubusercontent.com/4325054/65374641-7e0faf00-dc8c-11e9-89ad-bbed3c3b0375.png)

**Comment by jordens** [comment]
dds schematic looks good.

**Comment by jordens** [comment]
Also ensure SPI CLK digital cleanliness, maybe even using the same approaches as on Fastino.

**Comment by gkasprow** [comment]
I terminated all fast digital SDIO lines
