### ISSUE TITLE
Move DDS output termination resistors close to DDS, straighten bias

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#90]
The DAC outputs are high impedance and want their source termination close to them.
The eval board doesn't even use a defined diff pair impedance and instead just goes very close. According to ADI, improves SFDR.

![image](https://user-images.githubusercontent.com/1338946/107884256-501bb200-6ef4-11eb-9cae-6e39bf0ede31.png)

![image](https://user-images.githubusercontent.com/1338946/107884707-cae5cc80-6ef6-11eb-8230-2142e9991298.png)

![image](https://user-images.githubusercontent.com/1338946/107884770-15ffdf80-6ef7-11eb-9be3-137e09489725.png)

**Comment by gkasprow** [comment]
fixed 
![obraz](https://user-images.githubusercontent.com/4325054/110035223-aafa3980-7d3b-11eb-8f76-2eb31ac74351.png)

**Comment by jordens** [comment]
Thanks!
