### ISSUE TITLE
AD8065ARMZ (IC1) wrong P/N and footprint

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/Pounder#91]
The AMR suffix exists only for AD8066 (double opamp) where is a different pinout.
It has to be changed to AR (SOIC) or ART (SOT-23).
PCB needs to be modified.

![obraz](https://user-images.githubusercontent.com/25741678/109808656-af353280-7c27-11eb-92ff-4b3feca3ecb6.png)

![obraz](https://user-images.githubusercontent.com/25741678/109808699-ba885e00-7c27-11eb-995e-3d8e70cb00cb.png)

**Comment by gkasprow** [comment]
@mkiepiela was the PCB already produced? If so I can propose another amplifier. If not, I will change it to common SOIC.

**Comment by mkiepiela** [comment]
@gkasprow No, it was not manufactured yet. Please change the footprint.

**Comment by gkasprow** [comment]
ACK

**Comment by gkasprow** [comment]
fixed
