### ISSUE TITLE
J1, J10 wrong PNs in BOM

### ISSUE THREAD

**Issue by pkozakiewicz** [sinara-hw/Pounder#92]
Correct PNs are given in LibRef column.

**Comment by gkasprow** [comment]
right, it should be ESW-117-23-L-D

**Comment by gkasprow** [comment]
and ESW-113-23-L-D

**Comment by gkasprow** [comment]
It's clear now.
ESW-117-33-L-D-ND should be used with the original 3M connectors. They have 16.13 mm height; they need to be assembled in an elevated way
ESW-117-23-L-D should be used with IDC replacement connectors. They have a 13.59 mm height so will match the replacement connectors.

**Comment by gkasprow** [comment]
@pkozakiewicz I drafted a [new release ](https://github.com/sinara-hw/Pounder/releases/tag/v1.1rc3)

**Comment by pkozakiewicz** [comment]
@gkasprow Ok I'm launching the production now.
