### ISSUE TITLE
Temperature measurement with power detector

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#94]
The power detectors are reasonably close to the RF sections. I'd like to use them for temperature monitoring in a precision measurement. Let's connect their temperature PTAT output to the unused CPU ADC inputs.

* Appropriate voltage divider 5V to 3V.
* We can use IN2_N in single ended mode.
* IC10A TEMP to JADC1_IN2_N
* IC10B TEMP to JADC2_IN2_N

**Comment by jordens** [comment]
You are right. Divide to 2.048 V

**Comment by gkasprow** [comment]
2k and 3k are a bit low, but we already have them in BOM
![image](https://user-images.githubusercontent.com/4325054/181617413-e3e590fc-3708-4e6b-a14e-68e02a42f962.png)

**Comment by jordens** [comment]
@gkasprow I had another look.
For 125 C it would be 1.9 V max. And we have protection diodes there. Just go with 10k series. No divider needed.

![image](https://user-images.githubusercontent.com/1338946/181634595-325bb3bd-6eb5-4665-aabb-542b0624f25a.png)

**Comment by gkasprow** [comment]
OK
