### ISSUE TITLE
Power measurement redesign

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#95]
The power measurement circuit doesn't seem to work well. I'm mostly measurring ~1V output on the detector almost independent of how much power is at the input.

* The impedance isn't matched. The tap has 525 R output impedance towards the detecor, the detector has a 50 R input. One would think that's fine given the short (~20 mm) trace but it looks weird. Let's make it a proper discrete 1:10 (20 dB) splitter or use a integrated tap.
* Let's place the detector tap (R12, R17) after the preamps (IC2). No need to loose more precious power at the input. The working power range is also badly matched to what's typically available before the amplifier including the tap loss. With the tap after the amplifier we can do AGC and gain 32 dB of dynamic range on the detector for signal searching.
* The detectors (IC10) are pretty hungry (350 mW each). Can we use their power down interface with GPA7 and GPA6 of the gpio extender IC19?

**Comment by jordens** [comment]
* VTGT: Due to the input bias current and input impedance the voltage is 1.35 V (instead of 1.4 V), close to the minimum of 1.3 V. The eval board has a lower impedance divider (1k4 || 845R) than ours (5k6 || 3k6). Let's take the voltage divider from the eval board.

**Comment by jordens** [comment]
* The VOUT is 0-5 V (maybe 0-3 in practice) output. The JADC[12]_IN2_P are 0-2 V. Add a 2/5 voltage divider.

**Comment by gkasprow** [comment]
the TCM2 pin requires nearly 5V to disable the chip.
I used more common resistors to get 1.4V from 2.3V

![image](https://user-images.githubusercontent.com/4325054/181639663-86e4d3b4-f297-41af-b1a9-d1b1b10845c7.png)

**Comment by gkasprow** [comment]
@jordens I assume you are talking about such splitter
![image](https://user-images.githubusercontent.com/4325054/181641429-52895fd5-405b-487a-9360-36125a7d2fa6.png)

**Comment by gkasprow** [comment]
it has 20dB tap and 1.7dB insertion loss

**Comment by jordens** [comment]
Exactly. All R close together.

**Comment by MatBier** [comment]
@jordens @gkasprow 
I encountered a problem with power measurement when testing Pounder 1v2.
I've tested 3 boards and on all of them output voltage from power detector is stuck on max voltage (around 4.3V - 4.8V depending on the board). Output is not affected by variable input power and attenuation level. Problem seems to look like one from May 31, 2021 comment, but I also checked power measurements on one Pounder 1v0 board and I was able to detect it normally.

I changed resistor values in power splitter on one of 1v2 PCBs but it doesn't seem to help.

**Comment by jordens** [comment]
I haven't tested the new power detector design.

**Comment by jordens** [comment]
Maybe it's in power down mode?

**Comment by MatBier** [comment]
It is most definitely in operational mode, when in power down output is 0V.

**Comment by gkasprow** [comment]
The difference between these two designs is the way how RF signal is sourced.
New revision gets the signal after IC2 amplifier so it means it is nearly 30dB stronger. Instead of -26dBm -  20dB = 46dBm now we get 5dBm-20dB = -15dBm. That should be still within the range of the detector

**Comment by gkasprow** [comment]
we also changed the VTGT value from 1.35V to 1.4V. Please check if pin 12 is 1.4V

**Comment by gkasprow** [comment]
Please also check voltage on pins 1 and 16

**Comment by MatBier** [comment]
Turns out voltage on pin 12 is 0.88V. There is a mistake on the schematic - R16 and R63 values should be switched. With proper resistors power meter works properly.
