### ISSUE TITLE
Attenuator MISO level resistance.

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#97]
The attenuator is driving 5V into 1k5 + 50R and then MISO of the 3.3V CPU.

![image](https://user-images.githubusercontent.com/1338946/120205959-e1582f80-c22a-11eb-8e9c-0d908f7cc1aa.png)

1mA injected into the power rails still seems significant.
Can we increase that R41 resistance a bit to 10k? No need for speed. It's a slow bus.

c.f. #81

**Comment by gkasprow** [comment]
done

**Comment by gkasprow** [comment]
![image](https://user-images.githubusercontent.com/4325054/181605181-8bb3d882-4fde-4519-a326-0f066507208b.png)
