### ISSUE TITLE
Place output amplifiers

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#98]
My line of thought asking for the default no placement of the output amplifiers wasn't really smart.
Compared to other elements (e.g. the detectors) they consume a manageable amount of power. Let's mount them.

* Place IC11A IC11B R85A L15B
* DNP R86A R86B

**Comment by gkasprow** [comment]
done
![image](https://user-images.githubusercontent.com/4325054/181606147-983ea214-a9a7-4273-9e55-32ab7ecb9512.png)
