### ISSUE TITLE
IF amp filter and gain

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Pounder#99]
* This should read "0 dBm ..."
![image](https://user-images.githubusercontent.com/1338946/120206745-dbaf1980-c22b-11eb-9465-802bd3cdcf3f.png)

* At the sum mixer product (of >20 MHz) it's OK and beneficial to use very low impedance. That makes the mixer happy and also helps with suppressing recification in the opamp. Let's make a 10 MHz Chebyshev pi-filter:
  * DNP R22A,B
  * R62A,B = 49R4
  * R63A,B = 0R
  * C27A,B, C28A,B around 560 pF
  * L8A,B around 1 µH

* IMO the IF amp gain should be increased from 3 to 10 for all use cases:
  * Only the double-saturated use case of the mixer will get anywhere near 0 dBm output. All other use cases will need to stay significantly below (like -6 dBm).
  * We have the in-amp on Stabilizer that can cope fine with +-3V. Using low gain there also makes it faster and less noisy overall.

**Comment by jordens** [comment]
We could also consider a proper anti-aliasing lowpass here.

![image](https://user-images.githubusercontent.com/1338946/120283089-1b711200-c2bb-11eb-8af4-3f449f847709.png)

**Comment by jordens** [comment]
And I would like to consider a better noise match to the 50R mixer IF impedance. The FET opas are cool for high impedance sources but that's not what we have here. DC offset isn't a big problem since it's typically dwarfed by the mixer DC offset (~0.5 mV). Rectification to me seems to be the same effect as what the mixer itself would be limited by.

**Comment by gkasprow** [comment]
@jordens where would you put such LC anti-alias filter? Shall I add more LC sections before the opamp? I can add another placeholder for LC section.

**Comment by gkasprow** [comment]
In terms of an opamp, what about [ADA4896/7  ](https://www.analog.com/media/en/technical-documentation/data-sheets/ADA4896-2_4897-1_4897-2.PDF)

**Comment by jordens** [comment]
Let's go for this filter:

![image](https://user-images.githubusercontent.com/1338946/181640505-410443be-9be5-446a-9419-5a1956c6fd55.png)

* Plase that filter between mixer IF and opamp. The only resistor should be a RL = 50 R termination but after the filter. Keep C60 at the opamp input. R21=0R. Remove R9 traces (potential for annoying positive feedback). Make the opamp with gain=20 (to also lift it over the INA noise which is best case 18 nV/rtHz), cap its gain to 1 MHz.

![image](https://user-images.githubusercontent.com/1338946/181634957-555a7923-8dae-4ff1-84d1-27bd0a2e5a28.png)

* Make sure the mixer sum products (5-500 MHz) see low impedance (< 50R, can be capacitive). Shunt-first Chebychev helps here, but let's put a 33 pF in parallel to that first big shunt C.
* [ADA4896/7](https://www.analog.com/media/en/technical-documentation/data-sheets/ADA4896-2_4897-1_4897-2.PDF) looks good to me in gain=20

**Comment by gkasprow** [comment]
I got rid of the notch filter and other options to make space
![image](https://user-images.githubusercontent.com/4325054/181755274-f1736df5-86dc-4c96-9235-ff4eb83f8904.png)

**Comment by jordens** [comment]
Perfect
